import { Request, Response } from 'express';

export const roles: any[] = [
  {
    id: 'job-1', organisationId: 'default', title: 'Senior Full Stack Developer',
    department: 'Engineering', category: 'Software Engineering',
    location: 'Sydney, NSW (Hybrid)', employmentType: ['Full-time', 'Hybrid'],
    salaryMin: 130000, salaryMax: 160000, hideSalary: false,
    description: 'We are looking for a Senior Full-Stack Developer to lead engineering of our candidate-facing portal.',
    benefits: ['Health insurance', 'Learning budget $3000/year', 'Flexible hours'],
    requirementsMust: ['6+ years professional experience', 'Strong React and TypeScript', 'Node.js RESTful APIs'],
    requirementsNice: ['Open source contributions', 'Mentoring experience'],
    experienceLevel: 'Senior', experienceYearsMin: 6, experienceYearsMax: 15,
    skillsRequired: ['React', 'TypeScript', 'Node.js', 'AWS', 'Docker'],
    educationRequired: ["Bachelor's in Computer Science"],
    screeningQuestions: [
      'Describe your experience with high-performance React frontends.',
      'How do you approach API security in Node.js?',
      'Tell us about a challenging production incident you resolved.',
      'What are your salary expectations and notice period?'
    ],
    qualificationWeights: { locationWeight: 80, salaryWeight: 90, qualificationsWeight: 85, workRightsWeight: 95, skillsWeight: 100 },
    mandatoryQuestions: { locationCommute: true, workRights: true, salaryExpectation: true, yearsExperience: true, driversLicence: true },
    status: 'open', postedDate: '2026-05-15',
  },
  {
    id: 'job-2', organisationId: 'default', title: 'Product Manager — Platform',
    department: 'Product', category: 'Product Management',
    location: 'Melbourne, VIC (Hybrid)', employmentType: ['Full-time'],
    salaryMin: 120000, salaryMax: 150000, hideSalary: false,
    description: 'Lead product strategy and roadmap for our core platform.',
    benefits: ['Stock options', 'Flexible working', 'Health insurance'],
    requirementsMust: ['4+ years PM experience', 'B2B SaaS background', 'Data-driven decision making'],
    requirementsNice: ['Technical background', 'Startup experience'],
    experienceLevel: 'Senior', experienceYearsMin: 4, experienceYearsMax: 10,
    skillsRequired: ['Product Strategy', 'Agile', 'Analytics', 'Roadmapping'],
    educationRequired: ["Bachelor's in Business or Engineering"],
    screeningQuestions: [
      'How do you prioritise features with competing stakeholder requests?',
      'Describe a data-driven product decision you made.',
      'How do you work with engineering teams effectively?',
      'What are your salary expectations?'
    ],
    qualificationWeights: { locationWeight: 70, salaryWeight: 85, qualificationsWeight: 80, workRightsWeight: 90, skillsWeight: 85 },
    mandatoryQuestions: { locationCommute: true, workRights: true, salaryExpectation: true, yearsExperience: true, driversLicence: true },
    status: 'open', postedDate: '2026-05-18',
  },
  {
    id: 'job-3', organisationId: 'default', title: 'DevOps / Platform Engineer',
    department: 'Infrastructure', category: 'DevOps & Cloud',
    location: 'Remote (Australia)', employmentType: ['Full-time', 'Remote'],
    salaryMin: 120000, salaryMax: 145000, hideSalary: false,
    description: 'Own and scale our cloud infrastructure on AWS.',
    benefits: ['Fully remote', 'WFH setup allowance $2500', 'Health cover'],
    requirementsMust: ['Terraform', 'AWS', 'Kubernetes', '4+ years experience'],
    requirementsNice: ['Go or Python', 'Prometheus/Grafana'],
    experienceLevel: 'Mid', experienceYearsMin: 4, experienceYearsMax: 10,
    skillsRequired: ['Terraform', 'AWS', 'Kubernetes', 'Docker', 'CI/CD'],
    educationRequired: ["Bachelor's in Computer Science"],
    screeningQuestions: [
      'Describe your Kubernetes production experience.',
      'What are your Terraform best practices?',
      'Describe a major outage you handled.',
      'Do you have full Australian work rights? Salary expectation?'
    ],
    qualificationWeights: { locationWeight: 85, salaryWeight: 80, qualificationsWeight: 80, workRightsWeight: 100, skillsWeight: 90 },
    mandatoryQuestions: { locationCommute: true, workRights: true, salaryExpectation: true, yearsExperience: true, driversLicence: true },
    status: 'open', postedDate: '2026-05-20',
  },
  {
    id: 'job-4', organisationId: 'default', title: 'UX/UI Product Designer',
    department: 'Design', category: 'Product Design',
    location: 'Sydney, NSW (Flexible)', employmentType: ['Full-time', 'Hybrid'],
    salaryMin: 95000, salaryMax: 125000, hideSalary: false,
    description: 'Shape the visual language and user experience of our products.',
    benefits: ['Figma enterprise licence', 'Design conference budget'],
    requirementsMust: ['3+ years product design', 'Strong Figma skills', 'User research methodology'],
    requirementsNice: ['Frontend HTML/CSS', 'Motion design'],
    experienceLevel: 'Mid', experienceYearsMin: 3, experienceYearsMax: 8,
    skillsRequired: ['Figma', 'UX Research', 'Design Systems', 'Prototyping'],
    educationRequired: ["Degree in Design or HCI"],
    screeningQuestions: [
      'Walk us through your design process for a complex feature.',
      'How do you maintain a scalable design system?',
      'Describe a time engineering constraints changed your design.',
      'What is your salary expectation and notice period?'
    ],
    qualificationWeights: { locationWeight: 60, salaryWeight: 80, qualificationsWeight: 75, workRightsWeight: 85, skillsWeight: 90 },
    mandatoryQuestions: { locationCommute: true, workRights: true, salaryExpectation: true, yearsExperience: true, driversLicence: true },
    status: 'open', postedDate: '2026-05-22',
  },
  {
    id: 'job-5', organisationId: 'default', title: 'Data Scientist — AI/ML',
    department: 'AI Lab', category: 'Data Science',
    location: 'Melbourne, VIC (Office)', employmentType: ['Full-time'],
    salaryMin: 130000, salaryMax: 165000, hideSalary: false,
    description: 'Build and deploy ML models powering our candidate screening algorithms.',
    benefits: ['GPU compute budget', 'Conference sponsorships', 'Stock options'],
    requirementsMust: ['Python', 'PyTorch or TensorFlow', 'ML pipeline deployment', '4+ years experience'],
    requirementsNice: ['NLP/LLM experience', 'Published research'],
    experienceLevel: 'Senior', experienceYearsMin: 4, experienceYearsMax: 12,
    skillsRequired: ['Python', 'PyTorch', 'ML Pipelines', 'SQL', 'NLP'],
    educationRequired: ["Master's or PhD in CS or Mathematics"],
    screeningQuestions: [
      'How do you validate ML models for production?',
      'Describe your NLP or LLM experience.',
      'How do you handle model drift?',
      'Are you based in Melbourne? Salary expectation?'
    ],
    qualificationWeights: { locationWeight: 90, salaryWeight: 85, qualificationsWeight: 95, workRightsWeight: 90, skillsWeight: 100 },
    mandatoryQuestions: { locationCommute: true, workRights: true, salaryExpectation: true, yearsExperience: true, driversLicence: true },
    status: 'open', postedDate: '2026-05-24',
  },
  // ── ATLASSIAN JOBS (Sarah Chen) ──
  {
    id: 'job-6', organisationId: 'atlassian', recruiterId: 'recruiter@qani.io', company: 'Atlassian',
    title: 'Senior Backend Engineer — Jira', department: 'Engineering', category: 'Software Engineering',
    location: 'Sydney, NSW (Hybrid)', employmentType: ['Full-time', 'Hybrid'],
    salaryMin: 140000, salaryMax: 170000, hideSalary: false,
    description: 'Join Atlassian Jira team to build scalable backend services powering millions of users worldwide.',
    benefits: ['Generous equity', 'Health insurance', '$5000 learning budget', 'Flexible hours'],
    requirementsMust: ['5+ years backend engineering', 'Java or Kotlin expertise', 'Distributed systems experience', 'Australian work rights'],
    requirementsNice: ['Kafka experience', 'Kubernetes expertise', 'Open source contributions'],
    experienceLevel: 'Senior', experienceYearsMin: 5, experienceYearsMax: 12,
    skillsRequired: ['Java', 'Kotlin', 'PostgreSQL', 'Kafka', 'Kubernetes'],
    educationRequired: ["Bachelor's in Computer Science or equivalent"],
    screeningQuestions: ['Describe your experience with distributed systems at scale.', 'How do you approach database optimisation for high-traffic systems?', 'What is your notice period and salary expectation?', 'Are you based in Sydney or willing to relocate?'],
    qualificationWeights: { locationWeight: 80, salaryWeight: 90, qualificationsWeight: 85, workRightsWeight: 95, skillsWeight: 100 },
    mandatoryQuestions: { locationCommute: true, workRights: true, salaryExpectation: true, yearsExperience: true, driversLicence: true },
    status: 'open', postedDate: '2026-05-20',
  },
  {
    id: 'job-7', organisationId: 'atlassian', recruiterId: 'recruiter@qani.io', company: 'Atlassian',
    title: 'Engineering Manager — Confluence', department: 'Engineering', category: 'Engineering Leadership',
    location: 'Sydney, NSW (Hybrid)', employmentType: ['Full-time'],
    salaryMin: 180000, salaryMax: 220000, hideSalary: false,
    description: 'Lead a high-performing engineering team working on Confluence collaboration features.',
    benefits: ['Significant equity package', 'Health and wellness', 'Remote flexibility'],
    requirementsMust: ['3+ years engineering management', '8+ years software engineering', 'Experience managing teams of 6+', 'Australian work rights'],
    requirementsNice: ['SaaS product experience', 'Experience with OKRs'],
    experienceLevel: 'Lead', experienceYearsMin: 8, experienceYearsMax: 20,
    skillsRequired: ['Engineering Management', 'Agile', 'System Design', 'Hiring'],
    educationRequired: ["Bachelor's in Engineering or Computer Science"],
    screeningQuestions: ['How do you balance technical debt with feature delivery?', 'Describe a time you turned around an underperforming team.', 'What is your management philosophy?', 'Salary expectation and notice period?'],
    qualificationWeights: { locationWeight: 75, salaryWeight: 85, qualificationsWeight: 90, workRightsWeight: 95, skillsWeight: 80 },
    mandatoryQuestions: { locationCommute: true, workRights: true, salaryExpectation: true, yearsExperience: true, driversLicence: true },
    status: 'open', postedDate: '2026-05-22',
  },
  {
    id: 'job-8', organisationId: 'atlassian', recruiterId: 'recruiter@qani.io', company: 'Atlassian',
    title: 'Security Engineer — AppSec', department: 'Security', category: 'Cybersecurity',
    location: 'Remote (Australia)', employmentType: ['Full-time', 'Remote'],
    salaryMin: 150000, salaryMax: 180000, hideSalary: false,
    description: 'Help secure Atlassian product suite by building and running application security programs.',
    benefits: ['Full remote', 'Health insurance', 'Home office stipend $2000'],
    requirementsMust: ['4+ years application security', 'Penetration testing skills', 'OWASP expertise', 'Australian citizen or PR'],
    requirementsNice: ['Bug bounty program experience', 'Cloud security certifications'],
    experienceLevel: 'Senior', experienceYearsMin: 4, experienceYearsMax: 10,
    skillsRequired: ['AppSec', 'Penetration Testing', 'OWASP', 'Python', 'Burp Suite'],
    educationRequired: ["Bachelor's in Cybersecurity or related"],
    screeningQuestions: ['What is your approach to threat modelling?', 'Describe a critical vulnerability you discovered and how you handled it.', 'Are you an Australian citizen or permanent resident?', 'Salary expectation?'],
    qualificationWeights: { locationWeight: 70, salaryWeight: 85, qualificationsWeight: 90, workRightsWeight: 100, skillsWeight: 95 },
    mandatoryQuestions: { locationCommute: true, workRights: true, salaryExpectation: true, yearsExperience: true, driversLicence: true },
    status: 'open', postedDate: '2026-05-25',
  },
  {
    id: 'job-9', organisationId: 'atlassian', recruiterId: 'recruiter@qani.io', company: 'Atlassian',
    title: 'Data Engineer — Analytics Platform', department: 'Data', category: 'Data Engineering',
    location: 'Sydney, NSW (Hybrid)', employmentType: ['Full-time'],
    salaryMin: 125000, salaryMax: 155000, hideSalary: false,
    description: 'Build and maintain the data pipelines that power Atlassian analytics and reporting capabilities.',
    benefits: ['Health insurance', 'Learning budget', 'Flexible work'],
    requirementsMust: ['3+ years data engineering', 'Apache Spark or Flink', 'SQL mastery', 'Australian work rights'],
    requirementsNice: ['dbt experience', 'Real-time streaming experience'],
    experienceLevel: 'Mid', experienceYearsMin: 3, experienceYearsMax: 8,
    skillsRequired: ['Python', 'Spark', 'SQL', 'Airflow', 'AWS'],
    educationRequired: ["Bachelor's in Computer Science, Statistics or Engineering"],
    screeningQuestions: ['Describe a data pipeline you built from scratch.', 'How do you handle data quality issues in production?', 'What tools do you use for orchestration?', 'Salary expectation and location?'],
    qualificationWeights: { locationWeight: 80, salaryWeight: 88, qualificationsWeight: 85, workRightsWeight: 90, skillsWeight: 95 },
    mandatoryQuestions: { locationCommute: true, workRights: true, salaryExpectation: true, yearsExperience: true, driversLicence: true },
    status: 'open', postedDate: '2026-05-26',
  },
  {
    id: 'job-10', organisationId: 'atlassian', recruiterId: 'recruiter@qani.io', company: 'Atlassian',
    title: 'Technical Program Manager', department: 'Product', category: 'Program Management',
    location: 'Sydney, NSW (On-site)', employmentType: ['Full-time'],
    salaryMin: 135000, salaryMax: 165000, hideSalary: false,
    description: 'Drive cross-functional engineering programs across Atlassian platform initiatives.',
    benefits: ['Equity', 'Health insurance', 'Career development budget'],
    requirementsMust: ['5+ years TPM or program management', 'Engineering background', 'Stakeholder management', 'Australian work rights'],
    requirementsNice: ['PMP certification', 'Experience at a hyper-growth company'],
    experienceLevel: 'Senior', experienceYearsMin: 5, experienceYearsMax: 12,
    skillsRequired: ['Program Management', 'Jira', 'Agile', 'Risk Management', 'Communication'],
    educationRequired: ["Bachelor's in Engineering or Business"],
    screeningQuestions: ['How do you manage dependencies across multiple engineering teams?', 'Describe the largest program you have managed.', 'How do you handle scope creep?', 'Salary and availability?'],
    qualificationWeights: { locationWeight: 85, salaryWeight: 87, qualificationsWeight: 88, workRightsWeight: 90, skillsWeight: 82 },
    mandatoryQuestions: { locationCommute: true, workRights: true, salaryExpectation: true, yearsExperience: true, driversLicence: true },
    status: 'open', postedDate: '2026-05-27',
  },
  {
    id: 'job-11', organisationId: 'atlassian', recruiterId: 'recruiter@qani.io', company: 'Atlassian',
    title: 'iOS Engineer — Mobile Platform', department: 'Engineering', category: 'Mobile Engineering',
    location: 'Sydney, NSW (Hybrid)', employmentType: ['Full-time'],
    salaryMin: 130000, salaryMax: 160000, hideSalary: false,
    description: 'Build the next generation of Atlassian iOS apps used by millions of teams globally.',
    benefits: ['Health insurance', 'Learning budget', 'Latest Apple devices'],
    requirementsMust: ['4+ years iOS development', 'Swift expertise', 'App Store deployment experience', 'Australian work rights'],
    requirementsNice: ['Cross-platform Flutter or React Native experience', 'Accessibility expertise'],
    experienceLevel: 'Senior', experienceYearsMin: 4, experienceYearsMax: 10,
    skillsRequired: ['Swift', 'SwiftUI', 'Xcode', 'Core Data', 'REST APIs'],
    educationRequired: ["Bachelor's in Computer Science or equivalent"],
    screeningQuestions: ['What is your approach to iOS app architecture?', 'How do you optimise app performance?', 'Describe a complex UI you implemented on iOS.', 'Salary and notice period?'],
    qualificationWeights: { locationWeight: 80, salaryWeight: 88, qualificationsWeight: 85, workRightsWeight: 90, skillsWeight: 100 },
    mandatoryQuestions: { locationCommute: true, workRights: true, salaryExpectation: true, yearsExperience: true, driversLicence: true },
    status: 'open', postedDate: '2026-05-28',
  },
  {
    id: 'job-12', organisationId: 'atlassian', recruiterId: 'recruiter@qani.io', company: 'Atlassian',
    title: 'Solutions Engineer — Enterprise', department: 'Sales Engineering', category: 'Pre-Sales',
    location: 'Melbourne, VIC (Hybrid)', employmentType: ['Full-time'],
    salaryMin: 120000, salaryMax: 145000, hideSalary: false,
    description: 'Partner with enterprise sales to deliver technical demonstrations and solutions for Atlassian products.',
    benefits: ['Commission structure', 'Health insurance', 'Travel allowance'],
    requirementsMust: ['3+ years solutions engineering or pre-sales', 'Technical background', 'Excellent communication', 'Australian work rights'],
    requirementsNice: ['Atlassian product certifications', 'Cloud architecture knowledge'],
    experienceLevel: 'Mid', experienceYearsMin: 3, experienceYearsMax: 8,
    skillsRequired: ['Pre-Sales', 'Atlassian Suite', 'Cloud', 'Presentations', 'APIs'],
    educationRequired: ["Bachelor's in any field"],
    screeningQuestions: ['How do you handle a technical objection during a demo?', 'Describe a complex deal you helped close.', 'Are you based in Melbourne?', 'Salary expectation?'],
    qualificationWeights: { locationWeight: 85, salaryWeight: 85, qualificationsWeight: 80, workRightsWeight: 90, skillsWeight: 85 },
    mandatoryQuestions: { locationCommute: true, workRights: true, salaryExpectation: true, yearsExperience: true, driversLicence: true },
    status: 'open', postedDate: '2026-05-29',
  },
  // ── CANVA JOBS (James Morrison) ──
  {
    id: 'job-13', organisationId: 'canva', recruiterId: 'james.hr@techcorp.au', company: 'Canva',
    title: 'Frontend Engineer — Design Systems', department: 'Engineering', category: 'Frontend',
    location: 'Sydney, NSW (Hybrid)', employmentType: ['Full-time'],
    salaryMin: 135000, salaryMax: 165000, hideSalary: false,
    description: 'Build and evolve Canva design system used by billions of users and hundreds of internal teams.',
    benefits: ['Equity', 'Health and dental', 'Dog-friendly office', '$3000 learning budget'],
    requirementsMust: ['5+ years frontend engineering', 'React expertise', 'Design systems experience', 'Australian work rights'],
    requirementsNice: ['Figma experience', 'Accessibility expertise', 'Open source contributor'],
    experienceLevel: 'Senior', experienceYearsMin: 5, experienceYearsMax: 12,
    skillsRequired: ['React', 'TypeScript', 'CSS', 'Storybook', 'Design Tokens'],
    educationRequired: ["Bachelor's in CS or related"],
    screeningQuestions: ['How do you approach building accessible components?', 'Describe a design system you have built or maintained.', 'How do you handle breaking changes in a shared component library?', 'Salary and location?'],
    qualificationWeights: { locationWeight: 80, salaryWeight: 88, qualificationsWeight: 85, workRightsWeight: 90, skillsWeight: 100 },
    mandatoryQuestions: { locationCommute: true, workRights: true, salaryExpectation: true, yearsExperience: true, driversLicence: true },
    status: 'open', postedDate: '2026-05-21',
  },
  {
    id: 'job-14', organisationId: 'canva', recruiterId: 'james.hr@techcorp.au', company: 'Canva',
    title: 'Growth Marketing Manager', department: 'Marketing', category: 'Growth',
    location: 'Sydney, NSW (Hybrid)', employmentType: ['Full-time'],
    salaryMin: 110000, salaryMax: 140000, hideSalary: false,
    description: 'Drive user acquisition and retention strategies across Canva global markets.',
    benefits: ['Equity', 'Health insurance', 'Flexible work arrangements'],
    requirementsMust: ['4+ years growth or performance marketing', 'Data analytics proficiency', 'A/B testing expertise', 'Australian work rights'],
    requirementsNice: ['SaaS product marketing', 'SQL knowledge'],
    experienceLevel: 'Senior', experienceYearsMin: 4, experienceYearsMax: 10,
    skillsRequired: ['Growth Marketing', 'Analytics', 'A/B Testing', 'SEO', 'Paid Acquisition'],
    educationRequired: ["Bachelor's in Marketing, Business or related"],
    screeningQuestions: ['Describe a growth experiment that moved the needle significantly.', 'How do you prioritise growth initiatives?', 'What metrics do you focus on for user retention?', 'Salary expectation?'],
    qualificationWeights: { locationWeight: 80, salaryWeight: 85, qualificationsWeight: 85, workRightsWeight: 90, skillsWeight: 88 },
    mandatoryQuestions: { locationCommute: true, workRights: true, salaryExpectation: true, yearsExperience: true, driversLicence: true },
    status: 'open', postedDate: '2026-05-23',
  },
  {
    id: 'job-15', organisationId: 'canva', recruiterId: 'james.hr@techcorp.au', company: 'Canva',
    title: 'AI/ML Engineer — Content Intelligence', department: 'AI Lab', category: 'Machine Learning',
    location: 'Sydney, NSW (Hybrid)', employmentType: ['Full-time'],
    salaryMin: 155000, salaryMax: 195000, hideSalary: false,
    description: 'Build AI-powered content intelligence features that help users create better designs faster.',
    benefits: ['Top-of-market equity', 'GPU compute budget', 'Health insurance', 'Conference budget'],
    requirementsMust: ['4+ years ML engineering', 'LLM or generative AI experience', 'Python proficiency', 'Australian work rights'],
    requirementsNice: ['Computer vision experience', 'Published ML research', 'PyTorch expertise'],
    experienceLevel: 'Senior', experienceYearsMin: 4, experienceYearsMax: 12,
    skillsRequired: ['Python', 'PyTorch', 'LLMs', 'Computer Vision', 'MLOps'],
    educationRequired: ["Master's or PhD in ML, CS or related preferred"],
    screeningQuestions: ['Describe an LLM-powered feature you have shipped to production.', 'How do you evaluate generative AI quality at scale?', 'What is your experience with fine-tuning foundation models?', 'Salary expectation and notice period?'],
    qualificationWeights: { locationWeight: 75, salaryWeight: 85, qualificationsWeight: 95, workRightsWeight: 90, skillsWeight: 100 },
    mandatoryQuestions: { locationCommute: true, workRights: true, salaryExpectation: true, yearsExperience: true, driversLicence: true },
    status: 'open', postedDate: '2026-05-24',
  },
  {
    id: 'job-16', organisationId: 'canva', recruiterId: 'james.hr@techcorp.au', company: 'Canva',
    title: 'Staff Software Engineer — Infrastructure', department: 'Infrastructure', category: 'Platform',
    location: 'Remote (Australia)', employmentType: ['Full-time', 'Remote'],
    salaryMin: 170000, salaryMax: 210000, hideSalary: false,
    description: 'Define and build the infrastructure platform that powers Canva at global scale.',
    benefits: ['Full remote', 'Top equity package', 'Health insurance', 'Home office $3000'],
    requirementsMust: ['8+ years software engineering', '3+ years platform or infra engineering', 'Cloud architecture expertise', 'Australian work rights'],
    requirementsNice: ['Kubernetes operator development', 'eBPF knowledge'],
    experienceLevel: 'Staff', experienceYearsMin: 8, experienceYearsMax: 20,
    skillsRequired: ['Kubernetes', 'Terraform', 'Go', 'AWS', 'Observability'],
    educationRequired: ["Bachelor's in Computer Science or equivalent"],
    screeningQuestions: ['Describe a large-scale infrastructure migration you led.', 'How do you approach platform reliability?', 'What is your philosophy on infrastructure as code?', 'Salary and notice period?'],
    qualificationWeights: { locationWeight: 70, salaryWeight: 85, qualificationsWeight: 90, workRightsWeight: 90, skillsWeight: 100 },
    mandatoryQuestions: { locationCommute: true, workRights: true, salaryExpectation: true, yearsExperience: true, driversLicence: true },
    status: 'open', postedDate: '2026-05-25',
  },
  {
    id: 'job-17', organisationId: 'canva', recruiterId: 'james.hr@techcorp.au', company: 'Canva',
    title: 'Senior Product Designer — Presentations', department: 'Design', category: 'Product Design',
    location: 'Sydney, NSW (Hybrid)', employmentType: ['Full-time'],
    salaryMin: 120000, salaryMax: 150000, hideSalary: false,
    description: 'Shape the future of Canva presentations product used by millions to create stunning slides.',
    benefits: ['Equity', 'Design tool budget', 'Health insurance', 'Dog-friendly office'],
    requirementsMust: ['5+ years product design', 'Strong Figma skills', 'User research experience', 'Australian work rights'],
    requirementsNice: ['Animation or motion design', 'Experience designing for collaboration'],
    experienceLevel: 'Senior', experienceYearsMin: 5, experienceYearsMax: 12,
    skillsRequired: ['Figma', 'User Research', 'Prototyping', 'Design Systems', 'Usability Testing'],
    educationRequired: ["Bachelor's in Design, HCI or related"],
    screeningQuestions: ['Walk us through a product design project you are proud of.', 'How do you incorporate user research into your design process?', 'Describe how you handle design critique.', 'Salary and notice period?'],
    qualificationWeights: { locationWeight: 80, salaryWeight: 85, qualificationsWeight: 88, workRightsWeight: 90, skillsWeight: 95 },
    mandatoryQuestions: { locationCommute: true, workRights: true, salaryExpectation: true, yearsExperience: true, driversLicence: true },
    status: 'open', postedDate: '2026-05-26',
  },
  // ── SEEK JOBS (Emma Thompson) ──
  {
    id: 'job-18', organisationId: 'seek', recruiterId: 'emma.hr@seek.com.au', company: 'Seek',
    title: 'Senior Software Engineer — Search', department: 'Engineering', category: 'Search',
    location: 'Melbourne, VIC (Hybrid)', employmentType: ['Full-time'],
    salaryMin: 130000, salaryMax: 160000, hideSalary: false,
    description: 'Build the search and recommendation engine that helps millions of Australians find their next job.',
    benefits: ['Health insurance', 'Flexible work', 'Learning budget $3000', 'Parental leave 26 weeks'],
    requirementsMust: ['5+ years software engineering', 'Elasticsearch expertise', 'Backend engineering skills', 'Australian work rights'],
    requirementsNice: ['ML ranking experience', 'Solr knowledge'],
    experienceLevel: 'Senior', experienceYearsMin: 5, experienceYearsMax: 12,
    skillsRequired: ['Elasticsearch', 'Java', 'Python', 'Search Ranking', 'AWS'],
    educationRequired: ["Bachelor's in Computer Science"],
    screeningQuestions: ['Describe your experience with Elasticsearch at scale.', 'How do you approach relevance tuning?', 'Tell us about a search feature you built end to end.', 'Salary and are you in Melbourne?'],
    qualificationWeights: { locationWeight: 85, salaryWeight: 88, qualificationsWeight: 85, workRightsWeight: 90, skillsWeight: 100 },
    mandatoryQuestions: { locationCommute: true, workRights: true, salaryExpectation: true, yearsExperience: true, driversLicence: true },
    status: 'open', postedDate: '2026-05-20',
  },
  {
    id: 'job-19', organisationId: 'seek', recruiterId: 'emma.hr@seek.com.au', company: 'Seek',
    title: 'Product Manager — Candidate Experience', department: 'Product', category: 'Product Management',
    location: 'Melbourne, VIC (Hybrid)', employmentType: ['Full-time'],
    salaryMin: 115000, salaryMax: 145000, hideSalary: false,
    description: 'Own the product vision for Seek candidate-facing experience across web and mobile.',
    benefits: ['Health insurance', 'Flexible work', 'Share purchase plan', 'Gym membership'],
    requirementsMust: ['4+ years product management', 'Consumer product experience', 'Data-driven approach', 'Australian work rights'],
    requirementsNice: ['Mobile product experience', 'Marketplace product background'],
    experienceLevel: 'Senior', experienceYearsMin: 4, experienceYearsMax: 10,
    skillsRequired: ['Product Management', 'User Research', 'Analytics', 'Agile', 'Mobile'],
    educationRequired: ["Bachelor's in Business, Engineering or related"],
    screeningQuestions: ['How do you define and measure product success?', 'Describe a feature you killed and why.', 'How do you balance candidate needs vs employer needs in a marketplace?', 'Salary expectation?'],
    qualificationWeights: { locationWeight: 85, salaryWeight: 85, qualificationsWeight: 85, workRightsWeight: 90, skillsWeight: 85 },
    mandatoryQuestions: { locationCommute: true, workRights: true, salaryExpectation: true, yearsExperience: true, driversLicence: true },
    status: 'open', postedDate: '2026-05-22',
  },
  {
    id: 'job-20', organisationId: 'seek', recruiterId: 'emma.hr@seek.com.au', company: 'Seek',
    title: 'Data Analyst — Marketplace Insights', department: 'Data', category: 'Analytics',
    location: 'Melbourne, VIC (Hybrid)', employmentType: ['Full-time'],
    salaryMin: 95000, salaryMax: 120000, hideSalary: false,
    description: 'Analyse marketplace data to uncover insights that shape Seek product and business strategy.',
    benefits: ['Health insurance', 'Learning budget', 'Flexible work', 'Share plan'],
    requirementsMust: ['3+ years data analysis', 'SQL mastery', 'Python or R', 'Australian work rights'],
    requirementsNice: ['dbt', 'Tableau or Looker', 'Marketplace analytics experience'],
    experienceLevel: 'Mid', experienceYearsMin: 3, experienceYearsMax: 8,
    skillsRequired: ['SQL', 'Python', 'Tableau', 'Statistics', 'dbt'],
    educationRequired: ["Bachelor's in Statistics, Mathematics or related"],
    screeningQuestions: ['Describe an insight you surfaced that changed a business decision.', 'How do you communicate data findings to non-technical stakeholders?', 'What SQL techniques do you use for complex analysis?', 'Salary and location?'],
    qualificationWeights: { locationWeight: 88, salaryWeight: 88, qualificationsWeight: 85, workRightsWeight: 90, skillsWeight: 90 },
    mandatoryQuestions: { locationCommute: true, workRights: true, salaryExpectation: true, yearsExperience: true, driversLicence: true },
    status: 'open', postedDate: '2026-05-23',
  },
  {
    id: 'job-21', organisationId: 'seek', recruiterId: 'emma.hr@seek.com.au', company: 'Seek',
    title: 'Site Reliability Engineer', department: 'Infrastructure', category: 'SRE',
    location: 'Remote (Australia)', employmentType: ['Full-time', 'Remote'],
    salaryMin: 140000, salaryMax: 170000, hideSalary: false,
    description: 'Ensure Seek platform runs reliably for millions of job seekers and employers every day.',
    benefits: ['Full remote', 'On-call allowance', 'Health insurance', 'Home office stipend'],
    requirementsMust: ['4+ years SRE or DevOps', 'Kubernetes in production', 'Observability expertise', 'Australian work rights'],
    requirementsNice: ['Chaos engineering experience', 'SLO/SLI frameworks'],
    experienceLevel: 'Senior', experienceYearsMin: 4, experienceYearsMax: 12,
    skillsRequired: ['Kubernetes', 'Prometheus', 'Grafana', 'Terraform', 'Python'],
    educationRequired: ["Bachelor's in Computer Science or equivalent"],
    screeningQuestions: ['How do you approach incident response?', 'Describe how you have improved reliability at a previous company.', 'What is your experience with SLOs?', 'Salary and notice period?'],
    qualificationWeights: { locationWeight: 70, salaryWeight: 88, qualificationsWeight: 88, workRightsWeight: 90, skillsWeight: 95 },
    mandatoryQuestions: { locationCommute: true, workRights: true, salaryExpectation: true, yearsExperience: true, driversLicence: true },
    status: 'open', postedDate: '2026-05-25',
  },
  {
    id: 'job-22', organisationId: 'seek', recruiterId: 'emma.hr@seek.com.au', company: 'Seek',
    title: 'UX Researcher — Jobs Marketplace', department: 'Design', category: 'User Research',
    location: 'Melbourne, VIC (Hybrid)', employmentType: ['Full-time'],
    salaryMin: 105000, salaryMax: 130000, hideSalary: false,
    description: 'Conduct qualitative and quantitative research to deeply understand job seekers and employers on Seek.',
    benefits: ['Health insurance', 'Research tools budget', 'Flexible work', 'Parental leave'],
    requirementsMust: ['3+ years UX research', 'Mixed methods research skills', 'Stakeholder collaboration', 'Australian work rights'],
    requirementsNice: ['Marketplace research experience', 'Qualtrics or similar tools'],
    experienceLevel: 'Mid', experienceYearsMin: 3, experienceYearsMax: 8,
    skillsRequired: ['User Research', 'Usability Testing', 'Survey Design', 'Data Analysis', 'Figma'],
    educationRequired: ["Bachelor's in Psychology, HCI or Design"],
    screeningQuestions: ['Walk us through a research project that significantly impacted product direction.', 'How do you recruit research participants?', 'How do you handle conflicting findings from qual and quant research?', 'Salary and location?'],
    qualificationWeights: { locationWeight: 85, salaryWeight: 85, qualificationsWeight: 88, workRightsWeight: 90, skillsWeight: 88 },
    mandatoryQuestions: { locationCommute: true, workRights: true, salaryExpectation: true, yearsExperience: true, driversLicence: true },
    status: 'open', postedDate: '2026-05-26',
  },
  {
    id: 'job-23', organisationId: 'seek', recruiterId: 'emma.hr@seek.com.au', company: 'Seek',
    title: 'Customer Success Manager — Enterprise', department: 'Customer Success', category: 'Account Management',
    location: 'Sydney, NSW (Hybrid)', employmentType: ['Full-time'],
    salaryMin: 100000, salaryMax: 125000, hideSalary: false,
    description: 'Manage and grow Seek enterprise employer relationships, ensuring maximum value from the platform.',
    benefits: ['Commission structure', 'Health insurance', 'Car allowance', 'Flexible work'],
    requirementsMust: ['3+ years customer success or account management', 'B2B enterprise experience', 'Strong presentation skills', 'Australian work rights'],
    requirementsNice: ['SaaS platform experience', 'HR tech knowledge'],
    experienceLevel: 'Mid', experienceYearsMin: 3, experienceYearsMax: 8,
    skillsRequired: ['Account Management', 'CRM', 'Presentations', 'Negotiation', 'Analytics'],
    educationRequired: ["Bachelor's in Business or related"],
    screeningQuestions: ['How do you handle a high-risk churn situation with an enterprise client?', 'Describe your approach to quarterly business reviews.', 'Are you based in Sydney?', 'Salary expectation?'],
    qualificationWeights: { locationWeight: 85, salaryWeight: 85, qualificationsWeight: 82, workRightsWeight: 90, skillsWeight: 82 },
    mandatoryQuestions: { locationCommute: true, workRights: true, salaryExpectation: true, yearsExperience: true, driversLicence: true },
    status: 'open', postedDate: '2026-05-27',
  },
  {
    id: 'job-24', organisationId: 'seek', recruiterId: 'emma.hr@seek.com.au', company: 'Seek',
    title: 'Android Engineer — Mobile Apps', department: 'Engineering', category: 'Mobile',
    location: 'Melbourne, VIC (Hybrid)', employmentType: ['Full-time'],
    salaryMin: 125000, salaryMax: 155000, hideSalary: false,
    description: 'Build and ship the Seek Android app used by millions of job seekers across Australia and Asia.',
    benefits: ['Health insurance', 'Latest devices provided', 'Learning budget', 'Flexible work'],
    requirementsMust: ['4+ years Android development', 'Kotlin proficiency', 'Jetpack Compose experience', 'Australian work rights'],
    requirementsNice: ['Cross-platform experience', 'Performance optimisation expertise'],
    experienceLevel: 'Senior', experienceYearsMin: 4, experienceYearsMax: 10,
    skillsRequired: ['Kotlin', 'Jetpack Compose', 'Android SDK', 'REST APIs', 'CI/CD'],
    educationRequired: ["Bachelor's in Computer Science or equivalent"],
    screeningQuestions: ['Describe your experience with Jetpack Compose.', 'How do you approach app performance on low-end devices?', 'What is your testing strategy for Android apps?', 'Salary and are you in Melbourne?'],
    qualificationWeights: { locationWeight: 85, salaryWeight: 88, qualificationsWeight: 85, workRightsWeight: 90, skillsWeight: 100 },
    mandatoryQuestions: { locationCommute: true, workRights: true, salaryExpectation: true, yearsExperience: true, driversLicence: true },
    status: 'open', postedDate: '2026-05-28',
  },
  {
    id: 'job-25', organisationId: 'seek', recruiterId: 'emma.hr@seek.com.au', company: 'Seek',
    title: 'Finance Business Partner', department: 'Finance', category: 'Financial Planning',
    location: 'Melbourne, VIC (On-site)', employmentType: ['Full-time'],
    salaryMin: 110000, salaryMax: 135000, hideSalary: false,
    description: 'Partner with business leaders to drive financial planning, analysis and strategic decision making at Seek.',
    benefits: ['Health insurance', 'Flexible work', 'Professional development', 'Share plan'],
    requirementsMust: ['5+ years finance or FP&A', 'CPA or CA qualified', 'Advanced Excel and modelling', 'Australian work rights'],
    requirementsNice: ['Tech company experience', 'Power BI or Tableau'],
    experienceLevel: 'Senior', experienceYearsMin: 5, experienceYearsMax: 12,
    skillsRequired: ['FP&A', 'Excel', 'Financial Modelling', 'Power BI', 'SQL'],
    educationRequired: ["Bachelor's in Finance or Accounting, CPA or CA required"],
    screeningQuestions: ['Describe a financial model you built that influenced a major decision.', 'How do you communicate financial insights to non-finance leaders?', 'Are you CPA or CA qualified?', 'Salary expectation and are you in Melbourne?'],
    qualificationWeights: { locationWeight: 88, salaryWeight: 87, qualificationsWeight: 95, workRightsWeight: 90, skillsWeight: 85 },
    mandatoryQuestions: { locationCommute: true, workRights: true, salaryExpectation: true, yearsExperience: true, driversLicence: true },
    status: 'open', postedDate: '2026-05-29',
  },
];

export class RolesController {
  static async createRole(req: Request, res: Response) {
    try {
      const body = req.body;
      if (!body.title) {
        return res.status(400).json({ error: 'title required' });
      }
      const role = {
        id: `job-${Date.now()}`,
        organisationId: body.organisationId || 'default',
        ...body,
        createdAt: new Date().toISOString(),
      };
      roles.push(role);
      return res.status(201).json(role);
    } catch (error) {
      return res.status(500).json({ error: 'Failed to create role' });
    }
  }

  static async getRoles(req: Request, res: Response) {
    try {
      return res.json(roles);
    } catch (error) {
      return res.status(500).json({ error: 'Failed to fetch roles' });
    }
  }

  static async getRoleById(req: Request, res: Response) {
    try {
      const { id } = req.params;
      const role = roles.find(r => r.id === id);
      if (!role) return res.status(404).json({ error: 'Role not found' });
      return res.json(role);
    } catch (error) {
      return res.status(500).json({ error: 'Failed to fetch role' });
    }
  }

  static async updateRole(req: Request, res: Response) {
    try {
      const { id } = req.params;
      const idx = roles.findIndex(r => r.id === id);
      if (idx === -1) return res.status(404).json({ error: 'Role not found' });
      roles[idx] = { ...roles[idx], ...req.body };
      return res.json(roles[idx]);
    } catch (error) {
      return res.status(500).json({ error: 'Failed to update role' });
    }
  }

  static async deleteRole(req: Request, res: Response) {
    try {
      const { id } = req.params;
      const idx = roles.findIndex(r => r.id === id);
      if (idx === -1) return res.status(404).json({ error: 'Role not found' });
      roles.splice(idx, 1);
      return res.status(204).send();
    } catch (error) {
      return res.status(500).json({ error: 'Failed to delete role' });
    }
  }
}
